export enum IPreviewGif {
    default = -1,
    selectedPlayBgmName,
    selectedFinalStage,
    selectedSkyBox,
    selectedclearCountdownTimer,
    enemyModelPropMoveSpeed,
    enemyModelPropHpMax,
    enemyModelDamageSufferedZoneOfEnemyModelInvincibleTimeSec,
    objectsPoolModelCountLimit,
    onmyoBulletModelMoveDirectionX,
    onmyoBulletModelMoveDirectionY,
    onmyoBulletModelMoveSpeed,
    pentagramSystemModelAutoSpinSpeed,
    pentagramTurnTableViewAngleCorrectionValue,
    pentagramTurnTableModelDistance,
    playerModelPropMoveSpeed,
    playerModelPropHPMax,
    playerModelDamageSufferedZoneOfPlayerModelInvincibleTimeSec,
    wrapTurretModelMoveDirectionX,
    wrapTurretModelMoveDirectionY,
    graffitiTurretModelMoveDirectionX,
    graffitiTurretModelMoveDirectionY,
    sunMoonSystemModelDurations,
    levelDesignMainSkillLists,
    clearCountdownTimerCircleViewMaskAngle,
    shikigamiSkillSystemModelCandleInfoLimitCandleResorceMax,
    shikigamiSkillSystemModelCandleInfoRapidRecoveryTimeSec,
    pentagramSystemModelInputHistoriesLimit,
    // TODO:8.IDを追加
    downloadJson,
}
