export enum IPreviewGif {
    default = -1,
    selectedPlayBgmName,
    selectedFinalStage,
    selectedSkyBox,
    selectedclearCountdownTimer,
    enemyModelPropMoveSpeed,
    enemyModelPropHpMax,
    enemyModelDamageSufferedZoneOfEnemyModelInvincibleTimeSec,
    enemiesSpawnModelInvincibleTimeSec,
    objectsPoolModelCountLimit,
    onmyoBulletModelMoveDirectionX,
    onmyoBulletModelMoveDirectionY,
    onmyoBulletModelMoveSpeed,
    onmyoTurretModelInstanceRateTimeSec,
    pentagramSystemModelAutoSpinSpeed,
    pentagramTurnTableViewAngleCorrectionValue,
    pentagramTurnTableModelDistance,
    playerModelPropMoveSpeed,
    playerModelPropHPMax,
    playerModelDamageSufferedZoneOfPlayerModelInvincibleTimeSec,
    downloadJson
}
